# Generated by Django 5.1.7 on 2026-01-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
