# Generated by Django 5.1.7 on 2026-01-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_reason_alter_doctor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact',
            new_name='phone_number',
        ),
    ]
